# Generated by Django 5.2 on 2025-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('username', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=255)),
                ('gender', models.CharField(choices=[('option1', 'male'), ('option2', 'female'), ('option3', 'other')], max_length=10)),
                ('password', models.CharField(max_length=155)),
                ('gym_place', models.CharField(max_length=255)),
                ('pic', models.ImageField(blank=True, default='user-profile.png', upload_to='')),
                ('selection', models.JSONField()),
            ],
        ),
    ]
