# Generated by Django 5.2 on 2025-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=55)),
                ('sets', models.CharField(max_length=25)),
                ('reps', models.CharField(max_length=25)),
                ('image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
